import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'app.title': 'AI Synthesizer',
    'sidebar.knowledgeBase': 'Knowledge Base',
    'sidebar.all': 'All',
    'sidebar.socialMedia': 'Social Media',
    'sidebar.programming': 'Programming',
    'sidebar.life': 'Life',
    'sidebar.productivity': 'Productivity',
    'sidebar.business': 'Business',
    'sidebar.other': 'Other',
    'sidebar.footer': 'AI Knowledge Synthesizer © 2026',
    'input.placeholder': 'Paste content or link from Xiaohongshu, Douyin, or any article...',
    'input.submit': 'Auto Organize',
    'input.synthesizing': 'Synthesizing...',
    'input.shortcut': 'to submit',
    'card.deepDive': 'Deep Dive',
    'card.noCards': 'No knowledge cards yet',
    'card.startPrompt': 'Paste some content above to get started',
    'card.items': 'items',
    'deepDive.title': 'Deep Dive Report',
    'deepDive.researching': 'Researching:',
    'deepDive.loading': 'Researching across the web...',
    'deepDive.analyzing': 'Analyzing',
    'deepDive.sources': 'Sources & References',
    'deepDive.empty': 'Select a card to start a deep dive research.',
    'deepDive.footer': 'Generated by Gemini 3.0 with Google Search Grounding',
    'deepDive.error': 'Sorry, we couldn\'t complete the research at this time. Please try again later.',
  },
  zh: {
    'app.title': 'AI 知识合成器',
    'sidebar.knowledgeBase': '知识库',
    'sidebar.all': '全部',
    'sidebar.socialMedia': '自媒体',
    'sidebar.programming': '编程',
    'sidebar.life': '生活',
    'sidebar.productivity': '生产力',
    'sidebar.business': '商业',
    'sidebar.other': '未分类',
    'sidebar.footer': 'AI 知识合成器 © 2026',
    'input.placeholder': '请粘贴小红书/抖音的内容或链接，或任何文章...',
    'input.submit': '自动整理',
    'input.synthesizing': '正在合成...',
    'input.shortcut': '提交',
    'card.deepDive': '深度学习',
    'card.noCards': '暂无知识卡片',
    'card.startPrompt': '请在上方粘贴内容以开始',
    'card.items': '项',
    'deepDive.title': '深度学习报告',
    'deepDive.researching': '正在研究：',
    'deepDive.loading': '正在全网搜索...',
    'deepDive.analyzing': '正在分析',
    'deepDive.sources': '来源与参考',
    'deepDive.empty': '请选择一张卡片以开始深度学习研究。',
    'deepDive.footer': '由 Gemini 3.0 生成，基于 Google 搜索',
    'deepDive.error': '抱歉，暂时无法完成研究。请稍后再试。',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('zh'); // Default to Chinese as requested in the prompt context implies Chinese user

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
